# Generated by Django 4.2.9 on 2024-02-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='role',
            new_name='role_id',
        ),
    ]
