# Generated by Django 4.2.9 on 2024-02-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_rename_role_id_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
