# Generated by Django 4.2.9 on 2024-02-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cms.specialization'),
        ),
    ]
