# Generated by Django 4.2.9 on 2024-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_specialization_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
